In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install tensorflow opencv-python matplotlib pandas scikit-learn

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.12/dist-packages (4.13.0.92)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.1)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

In [ ]:
!mkdir /content/skin_dataset

In [ ]:
!unzip -q "/content/drive/MyDrive/Skin_lesion/raw_data/HAM10000_images_part_1.zip" -d /content/skin_dataset
!unzip -q "/content/drive/MyDrive/Skin_lesion/raw_data/HAM10000_images_part_2.zip" -d /content/skin_dataset

In [ ]:
import pandas as pd

tab_path = "/content/drive/MyDrive/Skin_lesion/raw_data/HAM10000_metadata.tab"
df = pd.read_csv(tab_path, sep='\t')

csv_path = "/content/skin_dataset/HAM10000_metadata.csv"
df.to_csv(csv_path, index=False)

print("Converted to CSV successfully")

Converted to CSV successfully

In [ ]:
import os

print("Number of images:",
      len([f for f in os.listdir('/content/skin_dataset') if f.endswith('.jpg')]))

Number of images: 10015

In [ ]:
IMAGE_DIR = "/content/skin_dataset"
CSV_PATH = "/content/skin_dataset/HAM10000_metadata.csv"

In [ ]:
import os
imgs = [f for f in os.listdir("/content/skin_dataset") if f.lower().endswith(".jpg")]
print("Images found:", len(imgs))
print("Sample:", imgs[:5])

Images found: 10015
Sample: ['ISIC_0034044.jpg', 'ISIC_0031117.jpg', 'ISIC_0025271.jpg', 'ISIC_0031568.jpg', 'ISIC_0031914.jpg']

In [ ]:
import pandas as pd

TAB_PATH = "/content/drive/MyDrive/Skin_lesion/raw_data/HAM10000_metadata.tab"
df = pd.read_csv(TAB_PATH, sep="\t")
print(df.shape)
df.head()

(10015, 8)

,lesion_id,image_id,dx,dx_type,age,sex,localization,dataset
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,vidir_modern
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,vidir_modern
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,vidir_modern
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,vidir_modern
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,vidir_modern

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df["dx"])

print("Classes:", list(le.classes_))
df[["image_id", "dx", "label"]].head()

Classes: ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']

       image_id   dx  label
0  ISIC_0027419  bkl      2
1  ISIC_0025030  bkl      2
2  ISIC_0026769  bkl      2
3  ISIC_0025661  bkl      2
4  ISIC_0031633  bkl      2

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df, test_size=0.2, stratify=df["label"], random_state=42
)

print("Train:", len(train_df), "Test:", len(test_df))

Train: 8012 Test: 2003

In [ ]:
import os

train_df = train_df.copy()
test_df = test_df.copy()

train_df["path"] = train_df["image_id"].apply(lambda x: os.path.join(IMAGE_DIR, x + ".jpg"))
test_df["path"]  = test_df["image_id"].apply(lambda x: os.path.join(IMAGE_DIR, x + ".jpg"))

In [ ]:
import os

IMAGE_DIR = "/content/skin_dataset"
train_df["path"] = train_df["image_id"].apply(lambda x: os.path.join(IMAGE_DIR, x + ".jpg"))
test_df["path"]  = test_df["image_id"].apply(lambda x: os.path.join(IMAGE_DIR, x + ".jpg"))

# keep only existing files (safety)
train_df = train_df[train_df["path"].apply(os.path.exists)]
test_df  = test_df[test_df["path"].apply(os.path.exists)]

print("Train usable:", len(train_df), "Test usable:", len(test_df))

Train usable: 8012 Test usable: 2003

In [ ]:
import tensorflow as tf

IMG_SIZE = 224
BATCH_SIZE = 16
AUTOTUNE = tf.data.AUTOTUNE

def decode_resize_normalize(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = tf.cast(img, tf.float32) / 255.0
    return img, label

In [ ]:
augmenter = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.15),
    tf.keras.layers.RandomZoom(0.10),
    tf.keras.layers.RandomContrast(0.10),
])

In [ ]:
def make_dataset(df, training=True):
    paths = df["path"].values
    labels = df["label"].values

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if training:
        ds = ds.shuffle(2000)

    ds = ds.map(decode_resize_normalize, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)

    if training:
        ds = ds.map(lambda x, y: (augmenter(x, training=True), y),
                    num_parallel_calls=AUTOTUNE)

    ds = ds.prefetch(AUTOTUNE)
    return ds

train_ds = make_dataset(train_df, training=True)
test_ds  = make_dataset(test_df, training=False)

print("Datasets ready ✅")

Datasets ready ✅

In [ ]:
base = tf.keras.applications.MobileNetV2(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base.trainable = False

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs * 255.0)
x = base(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(7, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ multiply (Multiply)             │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ true_divide (TrueDivide)        │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ subtract (Subtract)             │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 7)              │         8,967 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,266,951 (8.65 MB)

 Trainable params: 8,967 (35.03 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

In [ ]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=3, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint("best_model.keras", monitor="val_accuracy", save_best_only=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", patience=2, factor=0.5),
]

In [ ]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=8, restore_best_weights=True
    ),
    tf.keras.callbacks.ModelCheckpoint(
        "best_model.keras", monitor="val_loss", save_best_only=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss", patience=4, factor=0.5, min_lr=1e-7
    ),
]

In [ ]:
history1 = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=100,
    callbacks=callbacks
)

Epoch 1/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 660s 1s/step - accuracy: 0.6706 - loss: 1.0543 - val_accuracy: 0.7369 - val_loss: 0.7322 - learning_rate: 0.0010
Epoch 2/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 644s 1s/step - accuracy: 0.7247 - loss: 0.7754 - val_accuracy: 0.7184 - val_loss: 0.8052 - learning_rate: 0.0010
Epoch 3/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 647s 1s/step - accuracy: 0.7333 - loss: 0.7491 - val_accuracy: 0.7494 - val_loss: 0.7117 - learning_rate: 0.0010
Epoch 4/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 594s 1s/step - accuracy: 0.7374 - loss: 0.7233 - val_accuracy: 0.7494 - val_loss: 0.7310 - learning_rate: 0.0010
Epoch 5/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 646s 1s/step - accuracy: 0.7466 - loss: 0.6935 - val_accuracy: 0.7509 - val_loss: 0.7011 - learning_rate: 0.0010
Epoch 6/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 598s 1s/step - accuracy: 0.7526 - loss: 0.6757 - val_accuracy: 0.7494 - val_loss: 0.7392 - learning_rate: 0.0010
Epoch 7/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 638s 1s/step - accuracy: 0.7462 - loss: 0.6891 - val_accuracy: 0.7494 - val_loss: 0.7691 - learning_rate: 0.0010
Epoch 8/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 593s 1s/step - accuracy: 0.7590 - loss: 0.6796 - val_accuracy: 0.7544 - val_loss: 0.7314 - learning_rate: 0.0010
Epoch 9/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 646s 1s/step - accuracy: 0.7627 - loss: 0.6681 - val_accuracy: 0.7609 - val_loss: 0.7055 - learning_rate: 0.0010
Epoch 10/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 595s 1s/step - accuracy: 0.7655 - loss: 0.6435 - val_accuracy: 0.7649 - val_loss: 0.6767 - learning_rate: 5.0000e-04
Epoch 11/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 644s 1s/step - accuracy: 0.7746 - loss: 0.6208 - val_accuracy: 0.7683 - val_loss: 0.6944 - learning_rate: 5.0000e-04
Epoch 12/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 646s 1s/step - accuracy: 0.7823 - loss: 0.6127 - val_accuracy: 0.7434 - val_loss: 0.7296 - learning_rate: 5.0000e-04
Epoch 13/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 639s 1s/step - accuracy: 0.7746 - loss: 0.6304 - val_accuracy: 0.7664 - val_loss: 0.6835 - learning_rate: 5.0000e-04
Epoch 14/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 641s 1s/step - accuracy: 0.7806 - loss: 0.6069 - val_accuracy: 0.7624 - val_loss: 0.6899 - learning_rate: 5.0000e-04
Epoch 15/100
 88/501 ━━━━━━━━━━━━━━━━━━━━ 7:26 1s/step - accuracy: 0.7715 - loss: 0.6259

In [ ]:
base.trainable = True
for layer in base.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
history2 = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=50,          # you can set 100 also
    callbacks=callbacks
)

In [ ]:
import tensorflow as tf

model = tf.keras.models.load_model("best_model.keras")
print("Best model loaded ✅")

In [ ]:
import numpy as np
from sklearn.metrics import classification_report

y_true = []
y_pred = []

for x_batch, y_batch in test_ds:
    preds = model.predict(x_batch, verbose=0)
    y_true.extend(y_batch.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(7,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

In [ ]:
# Accuracy curve
plt.plot(history2.history['accuracy'], label='Train Accuracy')
plt.plot(history2.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy vs Epoch")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.show()

# Loss curve
plt.plot(history2.history['loss'], label='Train Loss')
plt.plot(history2.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss vs Epoch")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()

In [ ]:
model.save("skin_lesion_model.keras")
print("Model saved successfully ✅")